In [1]:
import numpy as np

In [2]:
x = np.arange(10)

In [3]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
x[np.array([3, 3, 1, 8])]

array([3, 3, 1, 8])

In [5]:
y = np.array([3, 3, 1, 8])

In [6]:
x[y]

array([3, 3, 1, 8])

In [7]:
x = x[y]

In [8]:
x

array([3, 3, 1, 8])

In [9]:
x[0]

3

In [10]:
x[1]

3

In [11]:
x[2]

1

In [13]:
x = np.arange(5)

In [14]:
x

array([0, 1, 2, 3, 4])

In [15]:
y = np.array([0, 7, 9, 20, 23])

In [16]:
y

array([ 0,  7,  9, 20, 23])

In [17]:
x = x[y]

IndexError: index 7 is out of bounds for axis 0 with size 5

In [18]:
y = y[x]

In [19]:
y

array([ 0,  7,  9, 20, 23])

In [20]:
x = np.array([1, 4, 4, 3, 0])

In [21]:
y = y[x]

In [22]:
y

array([ 7, 23, 23, 20,  0])